import { getPost, listPosts } from '@/lib/content/posts'
import type { Post } from '@/schemas/post'

export const SITE = {
  url: 'https://vtoivonen.com',
  name: 'Vilhelm Toivonen',
  title: 'Vilhelm Toivonen · AI Researcher',
  description:
    'Doctoral Researcher at University of Helsinki. Distributed LLMs: cognitive core, edge deployment, and tool-using agents.',
  author: 'Vilhelm Toivonen',
  twitter: '@ToivonenVilhelm',
  locale: 'en_US',
  // Default OG PNG generated at build time by `scripts/generate-og.mjs`.
  // Per-post PNGs live alongside it at `/og/<slug>.png`.
  ogImage: '/og/default.png',
} as const

export type PageMeta = {
  title: string
  description: string
  canonical: string
  ogType: 'website' | 'article'
  ogImage: string
  publishedAt?: string
  updatedAt?: string
  tags?: string[]
  jsonLd?: Record<string, unknown>
  robots?: string
  /** Open Graph locale override for non-English pages (e.g. 'fi_FI'). */
  locale?: string
  /** hreflang alternates for multi-language posts (includes x-default). */
  alternates?: Array<{ hrefLang: string; href: string }>
}

const OG_LOCALES: Record<string, string> = { en: 'en_US', fi: 'fi_FI' }

function absolute(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) return path
  const base = SITE.url.replace(/\/$/, '')
  const p = path.startsWith('/') ? path : `/${path}`
  return `${base}${p}`
}

export function getPageMeta(pathname: string): PageMeta {
  const path = pathname.replace(/\/+$/, '') || '/'

  if (path === '/') {
    return {
      title: SITE.title,
      description: SITE.description,
      canonical: absolute('/'),
      ogType: 'website',
      ogImage: absolute(SITE.ogImage),
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'Person',
        name: SITE.author,
        url: SITE.url,
        sameAs: [],
        jobTitle: 'Doctoral Researcher',
        affiliation: { '@type': 'Organization', name: 'University of Helsinki' },
      },
    }
  }

  if (path === '/search') {
    return {
      title: `Search · ${SITE.name}`,
      description: `Search every post on ${SITE.name}.`,
      canonical: absolute('/search'),
      ogType: 'website',
      ogImage: absolute(SITE.ogImage),
      robots: 'noindex,follow',
    }
  }

  if (path === '/blog') {
    return {
      title: `Writing · ${SITE.name}`,
      description:
        'Long-form notes on AI serving, quantization, and the machine-learning systems I build.',
      canonical: absolute('/blog'),
      ogType: 'website',
      ogImage: absolute(SITE.ogImage),
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'Blog',
        url: absolute('/blog'),
        name: `${SITE.name} · Writing`,
        author: { '@type': 'Person', name: SITE.author, url: SITE.url },
        blogPost: listPosts().map((p) => ({
          '@type': 'BlogPosting',
          url: absolute(p.permalink),
          headline: p.title,
          datePublished: p.publishedAt,
        })),
      },
    }
  }

  const blogMatch = path.match(/^\/blog\/([a-z0-9-]+)(?:\/([a-z]{2}))?$/)
  if (blogMatch) {
    const [, slug, lang] = blogMatch
    const post = getPost(slug, lang)
    if (post) return metaForPost(post)
  }

  return {
    title: SITE.title,
    description: SITE.description,
    canonical: absolute(path),
    ogType: 'website',
    ogImage: absolute(SITE.ogImage),
  }
}

function metaForPost(post: Post): PageMeta {
  const canonical = absolute(post.permalink)
  // Prefer a cover image if the post declares one, otherwise fall back to the
  // per-post OG PNG generated by scripts/generate-og.mjs at build time.
  // Language variants share the canonical slug's PNG.
  const ogImage = absolute(post.cover ?? `/og/${post.slug}.png`)
  // hreflang alternates for multi-language posts. The canonical language
  // lives at /blog/<slug>, variants at /blog/<slug>/<lang>; x-default points
  // at the canonical language.
  const defaultLang = post.languages[0]
  const hrefFor = (lang: string) =>
    absolute(lang === defaultLang ? `/blog/${post.slug}` : `/blog/${post.slug}/${lang}`)
  const alternates =
    post.languages.length > 1
      ? [
          ...post.languages.map((lang) => ({ hrefLang: lang, href: hrefFor(lang) })),
          { hrefLang: 'x-default', href: hrefFor(defaultLang) },
        ]
      : undefined
  return {
    locale: OG_LOCALES[post.lang],
    alternates,
    title: `${post.title} · ${SITE.name}`,
    description: post.summary,
    canonical,
    ogType: 'article',
    ogImage,
    publishedAt: post.publishedAt,
    updatedAt: post.updatedAt,
    tags: post.tags,
    robots: post.status === 'draft' ? 'noindex,nofollow' : undefined,
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: post.title,
      description: post.summary,
      datePublished: post.publishedAt,
      dateModified: post.updatedAt ?? post.publishedAt,
      author: { '@type': 'Person', name: SITE.author, url: SITE.url },
      inLanguage: post.lang,
      mainEntityOfPage: canonical,
      url: canonical,
      image: ogImage,
      keywords: post.tags?.join(', '),
      articleSection: post.category,
    },
  }
}

export function renderMetaTags(meta: PageMeta): string {
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const lines: string[] = []
  lines.push(`<title>${esc(meta.title)}</title>`)
  lines.push(`<meta name="description" content="${esc(meta.description)}" />`)
  lines.push(`<link rel="canonical" href="${esc(meta.canonical)}" />`)
  for (const alt of meta.alternates ?? []) {
    lines.push(`<link rel="alternate" hreflang="${esc(alt.hrefLang)}" href="${esc(alt.href)}" />`)
  }
  if (meta.robots) lines.push(`<meta name="robots" content="${esc(meta.robots)}" />`)
  // Open Graph
  lines.push(`<meta property="og:type" content="${meta.ogType}" />`)
  lines.push(`<meta property="og:url" content="${esc(meta.canonical)}" />`)
  lines.push(`<meta property="og:title" content="${esc(meta.title)}" />`)
  lines.push(`<meta property="og:description" content="${esc(meta.description)}" />`)
  lines.push(`<meta property="og:image" content="${esc(meta.ogImage)}" />`)
  lines.push(`<meta property="og:site_name" content="${esc(SITE.name)}" />`)
  lines.push(`<meta property="og:locale" content="${meta.locale ?? SITE.locale}" />`)
  if (meta.publishedAt)
    lines.push(`<meta property="article:published_time" content="${meta.publishedAt}" />`)
  if (meta.updatedAt)
    lines.push(`<meta property="article:modified_time" content="${meta.updatedAt}" />`)
  for (const tag of meta.tags ?? []) {
    lines.push(`<meta property="article:tag" content="${esc(tag)}" />`)
  }
  // Twitter
  lines.push(`<meta name="twitter:card" content="summary_large_image" />`)
  lines.push(`<meta name="twitter:url" content="${esc(meta.canonical)}" />`)
  lines.push(`<meta name="twitter:title" content="${esc(meta.title)}" />`)
  lines.push(`<meta name="twitter:description" content="${esc(meta.description)}" />`)
  lines.push(`<meta name="twitter:image" content="${esc(meta.ogImage)}" />`)
  lines.push(`<meta name="twitter:creator" content="${SITE.twitter}" />`)
  if (meta.jsonLd) {
    // JSON.stringify escapes the dangerous chars enough for a <script> body,
    // but we also defensively escape </script to avoid accidental tag break.
    const body = JSON.stringify(meta.jsonLd).replace(/<\/script/gi, '<\\/script')
    lines.push(`<script type="application/ld+json">${body}</script>`)
  }
  return lines.map((l) => `    ${l}`).join('\n')
}
